import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
    JigsawSwitchModule,
    JigsawListModule,
    JigsawMenuModule,
    JigsawButtonBarModule,
    JigsawNumericInputModule,
    JigsawHeaderModule,
    JigsawBreadcrumbModule,
    JigsawFishBoneModule,
    JigsawButtonModule,
    JigsawSelectModule,
    JigsawTagModule,
    JigsawInputModule,
    JigsawAutoCompleteInputModule,
    JigsawCheckBoxModule,
    JigsawRadioModule,
    JigsawRadioLiteModule,
    JigsawListLiteModule,
    JigsawLoadingModule,
    JigsawCollapseModule,
    JigsawTileLiteModule,
    JigsawTileSelectModule,
    JigsawComboSelectModule,
    JigsawIconModule,
    JigsawSearchInputModule,
    JigsawTextareaModule,
    JigsawSliderModule,
    JigsawDatePickerModule,
    JigsawDateTimePickerModule,
    JigsawTimePickerModule,
    JigsawDateTimeSelectModule,
    JigsawRangeDateTimePickerModule,
    JigsawRangeDateTimeSelectModule,
    JigsawTableModule,
    JigsawGraphModule,
    JigsawAlertModule,
    JigsawCascadeModule,
    JigsawTabsModule,
    JigsawPaginationModule,
    JigsawColorSelectModule,
    JigsawBadgeModule,
    JigsawUploadModule,
    JigsawTreeExtModule,
    JigsawChartIconModule,
    JigsawDialogModule,
    PopupService,
    JigsawDrawerModule,
    JigsawFloatModule,
    JigsawTransferModule,
    JigsawTooltipModule,
    JigsawRateModule,
    JigsawProgressModule,
    JigsawProcessStatusModule,
    JigsawStepsModule,
    JigsawTimeSectionModule,
    JigsawNotificationModule
} from "jigsaw/public_api";
import { JigsawDemoDescriptionModule } from "app/demo-description/demo-description";
import { ThemeBuildInThemeDemoComponent } from "./demo.component";

@NgModule({
    imports: [
        CommonModule, JigsawDemoDescriptionModule,
        JigsawHeaderModule,
        JigsawButtonModule,
        JigsawSelectModule,
        JigsawTagModule,
        JigsawInputModule,
        JigsawNumericInputModule,
        JigsawAutoCompleteInputModule,
        JigsawBreadcrumbModule,
        JigsawCheckBoxModule,
        JigsawRadioModule,
        JigsawRadioLiteModule,
        JigsawListModule,
        JigsawListLiteModule,
        JigsawLoadingModule,
        JigsawCollapseModule,
        JigsawTileLiteModule,
        JigsawTileSelectModule,
        JigsawSwitchModule,
        JigsawButtonBarModule,
        JigsawComboSelectModule,
        JigsawIconModule,
        JigsawSearchInputModule,
        JigsawTextareaModule,
        JigsawSliderModule,
        JigsawDatePickerModule,
        JigsawDateTimePickerModule,
        JigsawTimePickerModule,
        JigsawDateTimeSelectModule,
        JigsawRangeDateTimePickerModule,
        JigsawRangeDateTimeSelectModule,
        JigsawMenuModule,
        JigsawTableModule,
        JigsawGraphModule,
        JigsawAlertModule,
        JigsawCascadeModule,
        JigsawTabsModule,
        JigsawPaginationModule,
        JigsawColorSelectModule,
        JigsawFishBoneModule,
        JigsawBadgeModule,
        JigsawUploadModule,
        JigsawTreeExtModule,
        JigsawChartIconModule,
        JigsawDialogModule,
        JigsawDrawerModule,
        JigsawFloatModule,
        JigsawTransferModule,
        JigsawTooltipModule,
        JigsawRateModule,
        JigsawProgressModule,
        JigsawProcessStatusModule,
        JigsawStepsModule,
        JigsawTimeSectionModule,
        JigsawNotificationModule
    ],
    declarations: [ThemeBuildInThemeDemoComponent],
    exports: [ThemeBuildInThemeDemoComponent],
    providers: [PopupService]
})
export class ThemeBuildInThemeDemoModule {
}
